theme: jekyll-theme-minimal
title: Mohammed El Bouzrouti
description: Senior software engineer
logo: https://pbs.twimg.com/profile_images/1445158955995602944/8Yub9l-T_400x400.png
github:
  is_project_page: false
